### ISSUE TITLE
I was thinking about getting GameDB Pro but the free version keeps messing up

### ISSUE THREAD

**Issue by MostHated** [reefbarman/gamedb-unity-plugin#3]
Hello,
   I was considering getting your asset but I tried out the free version and anytime I try to add some fields and what not it messes up, the bottom part becomes no longer visible and then it doesn't save anything that I added. Unfortunately, that is definitely not something I am looking to have happen to my game data. Any idea what is up with that?

Thanks,

**Comment by reefbarman** [comment]
Thank you for letting me know. The free version doesn't get as much love which is a bit of a failing of mine. I am currently away on Holiday but will investigate when I get back and ensure it is fixed

**Comment by reefbarman** [comment]
Hi @MostHated,

I haven't been able to reproduce your issues. Could you help me out with some more information?

What version of Unity are you using? Do you have a video or screenshot of the issue and can I get hold of the JSON files for you gameDB?

Thank you

**Comment by MostHated** [comment]
I will try to see what I came come up with, I think at the time I was using 2017.3.0f3. I was trying to make a test weapon DB, I think it all started to act up when I went to add a prefab slot if I remember correctly. I will try to reinstall it, though my main project has since been updated to 2017.4, not sure if it will make a difference.

**Comment by reefbarman** [comment]
Hi,

Unfortunately I am going to have to close this issue as I haven't heard anything back and I have still been unable to reproduce it without further information.

If you manage to find reproduction steps please feel free to open the issue again

Thanks

**Comment by MostHated** [comment]
No worries man, my apologies I have not been able to get to it. I have been wrapped up in another project and have not had a need to revisit this. If I get back to my other one I will be sure to resubmit.
