### ISSUE TITLE
Unity 2018 and Assembly Files

### ISSUE THREAD

**Issue by OuicheDoctor** [reefbarman/gamedb-unity-plugin#4]
Hi,

First of all, thanks for this plugin, you did a good job ;-)

We've just bought the pro version of the GameDB plugin and I was looking to get the enums of the project in the GameDB. It seems that your using the standard Assembly-CSharp assembly. 

But with the Assembly Files feature, we have now several custom assemblies that may contains our enums. Will the plugin support the usage of Assembly Files in a near future ?

**Comment by reefbarman** [comment]
Hi there,

And thank you for the kind words, I am actually looking into supporting custom assemblies for the enums, just a few details I need to figure out before I can release the update! Keep your eyes on an update in the not too distant future

Thanks

**Comment by OuicheDoctor** [comment]
Nice, guess i'll just wait then ^^

On a different subject (tell me if I should make another thread on the topic) : your documentation mentions a zip archive for a remote server written in go, but I can't find it. 

Is it obsolete ? I saw that you still have an API to proceed to remote call. Do you have an example that I may try ?

**Comment by reefbarman** [comment]
The server zip is provided on request as I couldn't package it in the
asset, if you would like this please send me an email to the address on my
publisher page https://assetstore.unity.com/publishers/23742 and include
details of your purchase such as invoice number and purchase date so I can
verify your purchase and send you the server code
