### ISSUE TITLE
Running into an Error Message when importing

### ISSUE THREAD

**Issue by TeneBis** [reefbarman/gamedb-unity-plugin#5]
Unable to update following assemblies:Assets/Plugins/GameDBLibrary/GameDBLibrary.dll (Name = GameDBLibrary, Error = 131) (Output: C:\Users\rafae\AppData\Local\Temp\tmp23397b23.tmp)
[AssemblyUpdater] Member 'System.Boolean UnityEngine.Networking.UnityWebRequest::get_isError()' replaced with 'System.Boolean UnityEngine.Networking.UnityWebRequest::get_isNetworkError()' in method 'System.Void GameDBLibrary.WebRequest/<>c__DisplayClass3_0::<DoRequest>b__0()'.

I run into this error everytime I import the plugin, no matter how often I reinstall something.
Help would be appreciated

**Comment by reefbarman** [comment]
Hi, which version of Unity are you using? This plugin is really old and I haven't updated it since the Unity 5 days

**Comment by TeneBis** [comment]
Unity 2019.4.17f. If you dont think this plugin works with unity anymore, is there any other you can recommend?

**Comment by reefbarman** [comment]
Hi yeah it likely won't work with anything newer than Unity 5, and unfortunetaly I don't have any recommendations as I'm not very active in the community anymore sorry
